### PR TITLE
1.20.4 Update

### PR DESCRIPTION
**Pull request by GomorrhaDev**
Hi, wonderful tool which I will definitely use in my plugins! I have updated it to 1.20.4, I hope everything works.

### CODE REVIEW

**Comment by GomorrhaDev** [comment]
Oh and github generated all the html documents itself, so sorry for all the files changed. @hmzel

**Comment by GomorrhaDev** [comment]
@hmzel

**Comment by GomorrhaDev** [comment]
@hmzel

**Comment by GomorrhaDev** [comment]
@hmzel ):

**Comment by Ticha22608** [comment]
yeah @hmzel where's 1.20.4 NERD....

**Comment by hmzel** [comment]
hi! sorry, the past few months have been rather hectic for me- i'll start updating this and review this pull request soon, probably within the next week

**Review by hazeldritch — APPROVED** [review]

**Pull request merged**
